# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(),
        ),
    ]
