# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 05:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180601_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
